// features/transfers/mocks.ts
import { TransferRow } from "./types";

export const transferRows: TransferRow[] = [
  {
    id: 1,
    player: "Жомарт",
    age: 36,
    team: "ТД Есиль",
    position: "НАП",
    league: "Супер-лига",
    status: "free",
    cost: "100000",
    salary: "10000",
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: 2,
    player: "Cristiano Ronaldo",
    age: 36,
    team: "Al-Nassr",
    position: "ПЗЩ",
    league: "Супер-лига",
    status: "transfer",
    cost: "120",
    salary: "55.000",
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: 3,
    player: "Neymar Jr.",
    age: 27,
    team: "Paris Saint-Germain",
    position: "ЗАЩ",
    league: "Супер-лига",
    status: "free",
    cost: "110",
    salary: "48.000",
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: 4,
    player: "Kevin De Bruyne",
    age: 30,
    team: "Manchester City",
    position: "ВР",
    league: "Супер-лига",
    status: "transfer",
    cost: "90",
    salary: "45.000",
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: 5,
    player: "Robert Lewandowski",
    age: 35,
    team: "Barcelona",
    position: "ЗАЩ",
    league: "Супер-лига",
    status: "contract",
    cost: "95",
    salary: "47.000",
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: 6,
    player: "Kylian Mbappé",
    age: 25,
    team: "Paris Saint-Germain",
    position: "ПЗЩ",
    league: "Супер-лига",
    status: "transfer",
    cost: "130",
    salary: "60.000",
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: 7,
    player: "Erling Haaland",
    age: 23,
    team: "Manchester City",
    position: "НАП",
    league: "Супер-лига",
    status: "transfer",
    cost: "125",
    salary: "58.000",
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: 8,
    player: "Mohamed Salah",
    age: 31,
    team: "Liverpool",
    position: "НАП",
    league: "Супер-лига",
    status: "free",
    cost: "115",
    salary: "52.000",
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: 9,
    player: "Virgil van Dijk",
    age: 32,
    team: "Liverpool",
    position: "ЗАЩ",
    league: "Супер-лига",
    status: "contract",
    cost: "85",
    salary: "40.000",
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: 10,
    player: "Luka Modrić",
    age: 38,
    team: "Real Madrid",
    position: "ЗАЩ",
    league: "Супер-лига",
    status: "contract",
    cost: "80",
    salary: "42.000",
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: 11,
    player: "Karim Benzema",
    age: 36,
    team: "Al-Ittihad",
    position: "НАП",
    league: "Супер-лига",
    status: "contract",
    cost: "105",
    salary: "50.000",
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: 12,
    player: "Pedri",
    age: 21,
    team: "Barcelona",
    position: "ПЗЩ",
    league: "Супер-лига",
    status: "contract",
    cost: "75",
    salary: "38.000",
    image: require("@/assets/images/adaptive-icon.png"),
  },
];
