// features/league/mocks.ts
import { LeagueRow } from "./types";

export const leagueMock: LeagueRow[] = [
  {
    id: "bltk",
    pos: 1,
    name: "БИИК Шымкент",
    lastScore: { gf: 0, ga: 3 },
    played: 17,
    goalsFor: 172,
    goalsAgainst: 6,
    points: 46,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "akt",
    pos: 2,
    name: "Актобе",
    played: 15,
    goalsFor: 125,
    goalsAgainst: 4,
    points: 43,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "tom",
    pos: 3,
    name: "Tomiris-Turan",
    lastScore: { gf: 5, ga: 1 },
    played: 16,
    goalsFor: 77,
    goalsAgainst: 17,
    points: 37,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "kai",
    pos: 4,
    name: "Кайрат",
    played: 16,
    goalsFor: 50,
    goalsAgainst: 35,
    points: 33,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "eli",
    pos: 5,
    name: "Елимай",
    posDiff: +1,
    lastScore: { gf: 3, ga: 3 },
    played: 16,
    goalsFor: 40,
    goalsAgainst: 29,
    points: 29,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
];