// features/league/mocks.ts
import { LeagueRow } from "./types";

export const leagueMock: LeagueRow[] = [
  {
    id: "bltk",
    pos: 1,
    name: "БИИК Шымкент",
    lastScore: { gf: 0, ga: 3 },
    played: 17,
    goalsFor: 172,
    goalsAgainst: 6,
    points: 46,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "akt",
    pos: 2,
    name: "Актобе",
    played: 15,
    goalsFor: 125,
    goalsAgainst: 4,
    points: 43,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "tom",
    pos: 3,
    name: "Tomiris-Turan",
    lastScore: { gf: 5, ga: 1 },
    played: 16,
    goalsFor: 77,
    goalsAgainst: 17,
    points: 37,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "kai",
    pos: 4,
    name: "Кайрат",
    played: 16,
    goalsFor: 50,
    goalsAgainst: 35,
    points: 33,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "eli",
    pos: 5,
    name: "Елимай",
    posDiff: +1,
    lastScore: { gf: 3, ga: 3 },
    played: 16,
    goalsFor: 40,
    goalsAgainst: 29,
    points: 29,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "ord",
    pos: 6,
    name: "Ордабасы",
    posDiff: -1,
    lastScore: { gf: 1, ga: 2 },
    played: 16,
    goalsFor: 35,
    goalsAgainst: 32,
    points: 27,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "ast",
    pos: 7,
    name: "Астана",
    played: 15,
    goalsFor: 42,
    goalsAgainst: 28,
    points: 25,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "tur",
    pos: 8,
    name: "Туран",
    lastScore: { gf: 2, ga: 2 },
    played: 16,
    goalsFor: 38,
    goalsAgainst: 40,
    points: 23,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "tar",
    pos: 9,
    name: "Тараз",
    posDiff: +2,
    lastScore: { gf: 4, ga: 0 },
    played: 16,
    goalsFor: 31,
    goalsAgainst: 35,
    points: 21,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "aty",
    pos: 10,
    name: "Атырау",
    posDiff: -1,
    played: 15,
    goalsFor: 28,
    goalsAgainst: 38,
    points: 19,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "kyz",
    pos: 11,
    name: "Кызылжар",
    lastScore: { gf: 1, ga: 3 },
    played: 16,
    goalsFor: 25,
    goalsAgainst: 45,
    points: 17,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "okz",
    pos: 12,
    name: "Окжетпес",
    posDiff: -2,
    lastScore: { gf: 0, ga: 1 },
    played: 16,
    goalsFor: 22,
    goalsAgainst: 48,
    points: 15,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "irty",
    pos: 13,
    name: "Иртыш",
    played: 15,
    goalsFor: 19,
    goalsAgainst: 52,
    points: 12,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "ksp",
    pos: 14,
    name: "Каспий",
    lastScore: { gf: 2, ga: 5 },
    played: 16,
    goalsFor: 18,
    goalsAgainst: 58,
    points: 10,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
  {
    id: "mak",
    pos: 15,
    name: "Макталарал",
    posDiff: +1,
    lastScore: { gf: 1, ga: 1 },
    played: 16,
    goalsFor: 15,
    goalsAgainst: 62,
    points: 8,
    crest: require("@/assets/images/adaptive-icon.png"),
  },
];