import { ClubRating, PlayerRating } from "./types";

export const clubRatingMock: ClubRating[] = [
  {
    id: "1",
    name: "Кайрат",
    position: 1,
    points: 67,
    change: 0,
    logo: require("@/assets/images/adaptive-icon.png"),
    played: 26,
    won: 21,
    drawn: 4,
    lost: 1,
    goalsFor: 68,
    goalsAgainst: 15,
    goalDifference: 53,
  },
  {
    id: "2",
    name: "Астана",
    position: 2,
    points: 64,
    change: 1,
    logo: require("@/assets/images/adaptive-icon.png"),
    played: 26,
    won: 20,
    drawn: 4,
    lost: 2,
    goalsFor: 62,
    goalsAgainst: 18,
    goalDifference: 44,
  },
  {
    id: "3",
    name: "Шахтер",
    position: 3,
    points: 58,
    change: -1,
    logo: require("@/assets/images/adaptive-icon.png"),
    played: 26,
    won: 18,
    drawn: 4,
    lost: 4,
    goalsFor: 54,
    goalsAgainst: 22,
    goalDifference: 32,
  },
  {
    id: "4",
    name: "Актобе",
    position: 4,
    points: 52,
    change: 0,
    logo: require("@/assets/images/adaptive-icon.png"),
    played: 26,
    won: 16,
    drawn: 4,
    lost: 6,
    goalsFor: 48,
    goalsAgainst: 26,
    goalDifference: 22,
  },
  {
    id: "5",
    name: "Тобол",
    position: 5,
    points: 48,
    change: 1,
    logo: require("@/assets/images/adaptive-icon.png"),
    played: 26,
    won: 14,
    drawn: 6,
    lost: 6,
    goalsFor: 42,
    goalsAgainst: 28,
    goalDifference: 14,
  },
];

export const playerRatingMock: PlayerRating[] = [
  {
    id: "1",
    name: "Исламхан Омар",
    position: 1,
    club: "Кайрат",
    clubLogo: require("@/assets/images/adaptive-icon.png"),
    avatar: require("@/assets/images/adaptive-icon.png"),
    points: 245,
    change: 0,
    goals: 18,
    assists: 12,
    matches: 24,
    rating: 8.2,
  },
  {
    id: "2",
    name: "Абат Айтыхожин",
    position: 2,
    club: "Астана",
    clubLogo: require("@/assets/images/adaptive-icon.png"),
    avatar: require("@/assets/images/adaptive-icon.png"),
    points: 238,
    change: 1,
    goals: 16,
    assists: 14,
    matches: 25,
    rating: 8.0,
  },
  {
    id: "3",
    name: "Максим Федоров",
    position: 3,
    club: "Шахтер",
    clubLogo: require("@/assets/images/adaptive-icon.png"),
    avatar: require("@/assets/images/adaptive-icon.png"),
    points: 232,
    change: -1,
    goals: 15,
    assists: 11,
    matches: 23,
    rating: 7.9,
  },
  {
    id: "4",
    name: "Нурлан Нуркенов",
    position: 4,
    club: "Актобе",
    clubLogo: require("@/assets/images/adaptive-icon.png"),
    avatar: require("@/assets/images/adaptive-icon.png"),
    points: 225,
    change: 0,
    goals: 14,
    assists: 9,
    matches: 22,
    rating: 7.7,
  },
  {
    id: "5",
    name: "Данияр Утешов",
    position: 5,
    club: "Тобол",
    clubLogo: require("@/assets/images/adaptive-icon.png"),
    avatar: require("@/assets/images/adaptive-icon.png"),
    points: 218,
    change: 2,
    goals: 13,
    assists: 8,
    matches: 21,
    rating: 7.5,
  },
];