import { TeamRatingRow } from "./types";

export const teamRatingRows: TeamRatingRow[] = [
  {
    teamName: "БИИК Шымкент",
    cityName: "Шымкент",
    league: "Мастер-лига",
    season1: 30,
    season2: 31,
    season3: 33,
    season4: 42,
    total: 136,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Актобе",
    cityName: "Актобе",
    league: "Мастер-лига",
    season1: 28,
    season2: 32,
    season3: 34,
    season4: 39,
    total: 133,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Tomiris-Turan",
    cityName: "Туркестан",
    league: "Мастер-лига",
    season1: 27,
    season2: 29,
    season3: 30,
    season4: 35,
    total: 121,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Кайрат",
    cityName: "Алматы",
    league: "Мастер-лига",
    season1: 25,
    season2: 28,
    season3: 29,
    season4: 33,
    total: 115,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Елимай",
    cityName: "Семей",
    league: "Мастер-лига",
    season1: 24,
    season2: 26,
    season3: 28,
    season4: 31,
    total: 109,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Кызылжар",
    cityName: "Петропавловск",
    league: "Мастер-лига",
    season1: 23,
    season2: 24,
    season3: 26,
    season4: 30,
    total: 103,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Улытай",
    cityName: "Жезказган",
    league: "Мастер-лига",
    season1: 22,
    season2: 23,
    season3: 25,
    season4: 28,
    total: 98,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Zhenis Astana",
    cityName: "Астана",
    league: "Мастер-лига",
    season1: 21,
    season2: 22,
    season3: 24,
    season4: 27,
    total: 94,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Тобол",
    cityName: "Костанай",
    league: "Мастер-лига",
    season1: 19,
    season2: 21,
    season3: 22,
    season4: 25,
    total: 87,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Астана test 1",
    cityName: "Астана test 1",
    league: "Мастер-лига",
    season1: 18,
    season2: 20,
    season3: 21,
    season4: 23,
    total: 82,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Астана test 2",
    cityName: "Астана test 2",
    league: "Мастер-лига",
    season1: 18,
    season2: 20,
    season3: 21,
    season4: 23,
    total: 82,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Астана test 3",
    cityName: "Астана test 3",
    league: "Мастер-лига",
    season1: 18,
    season2: 20,
    season3: 21,
    season4: 23,
    total: 82,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Астана test 4",
    cityName: "Астана test 4",
    league: "Мастер-лига",
    season1: 18,
    season2: 20,
    season3: 21,
    season4: 23,
    total: 82,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Астана test 5",
    cityName: "Астана test 5",
    league: "Мастер-лига",
    season1: 18,
    season2: 20,
    season3: 21,
    season4: 23,
    total: 82,
    image: require("@/assets/images/adaptive-icon.png"),
  },
  {
    teamName: "Астана test 6",
    cityName: "Астана test 6",
    league: "Мастер-лига",
    season1: 18,
    season2: 20,
    season3: 21,
    season4: 23,
    total: 82,
    image: require("@/assets/images/adaptive-icon.png"),
  },
];
